version: '3.8'

services:
  readnwin-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
    volumes:
      # Mount uploads directory to persist files
      - ./public/uploads:/app/public/uploads:rw
      - ./uploads:/app/uploads:rw
      - ./storage:/app/storage:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s