version: '3.8'

services:
  readnwin-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # Database Configuration
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      # NextAuth Configuration
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      # Payment Gateway Configuration
      - FLUTTER_WAVE_HASH=${FLUTTER_WAVE_HASH}
      - RAVE_LIVE_PUBLIC_KEY=${RAVE_LIVE_PUBLIC_KEY}
      - RAVE_LIVE_SECRET_KEY=${RAVE_LIVE_SECRET_KEY}
      # Email Configuration
      - RESEND_API_KEY=${RESEND_API_KEY}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      # Timezone
      - TZ=${TZ:-Africa/Lagos}
    env_file:
      - .env.production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - readnwin-network

networks:
  readnwin-network:
    driver: bridge 