#!/bin/bash
# Auto-generated script to remove unused components
# Review before running!

echo "🗑️  Removing unused components..."

echo "Removing BookDataTable..."
rm "components/BookDataTable.tsx"
echo "Removing BookFiltersPanel..."
rm "components/BookFiltersPanel.tsx"
echo "Removing BookUploadModal..."
rm "components/BookUploadModal.tsx"
echo "Removing BookUploadModalV2..."
rm "components/BookUploadModalV2.tsx"
echo "Removing CategoryFilter..."
rm "components/CategoryFilter.tsx"
echo "Removing CategoryGrid..."
rm "components/CategoryGrid.tsx"
echo "Removing EnhancedBookManagement..."
rm "components/EnhancedBookManagement.tsx"
echo "Removing FlutterwaveScriptLoader..."
rm "components/FlutterwaveScriptLoader.tsx"
echo "Removing NewReleases..."
rm "components/NewReleases.tsx"
echo "Removing PersonalizedRecommendations..."
rm "components/PersonalizedRecommendations.tsx"
echo "Removing RichTextEditor..."
rm "components/RichTextEditor.tsx"
echo "Removing WorkModal..."
rm "components/WorkModal.tsx"
echo "Removing admin/BookUploadModal..."
rm "components/admin/BookUploadModal.tsx"
echo "Removing admin/EnhancedBookUploadForm..."
rm "components/admin/EnhancedBookUploadForm.tsx"
echo "Removing admin/ImageViewerModal..."
rm "components/admin/ImageViewerModal.tsx"
echo "Removing checkout/AddressForm..."
rm "components/checkout/AddressForm.tsx"
echo "Removing checkout/EnhancedShippingAddress..."
rm "components/checkout/EnhancedShippingAddress.tsx"
echo "Removing checkout/EnhancedShippingMethod..."
rm "components/checkout/EnhancedShippingMethod.tsx"
echo "Removing checkout/OrderConfirmation..."
rm "components/checkout/OrderConfirmation.tsx"
echo "Removing checkout/PaymentForm..."
rm "components/checkout/PaymentForm.tsx"
echo "Removing checkout/PaymentStatus..."
rm "components/checkout/PaymentStatus.tsx"
echo "Removing checkout/ShippingMethod..."
rm "components/checkout/ShippingMethod.tsx"
echo "Removing ui/EnhancedLoadingExample..."
rm "components/ui/EnhancedLoadingExample.tsx"
echo "Removing ui/ErrorBoundary..."
rm "components/ui/ErrorBoundary.tsx"
echo "Removing ui/NavigationLoader..."
rm "components/ui/NavigationLoader.tsx"
echo "Removing ui/SearchableDropdown..."
rm "components/ui/SearchableDropdown.tsx"

echo "✅ Cleanup complete!"
